#!/usr/bin/python3 -u

import fcntl
import os
import tempfile
import sys
import subprocess

from git_slug.refsdata import RemoteRefsData
from git_slug.gitconst import REFREPO, REFFILE, WATCHDIR
from git_slug.gitrepo import GitRepo


data = sys.stdin.readlines()

mail = subprocess.Popen(["./hooks/mailnotification"], stdin=subprocess.PIPE)
for line in data:
    mail.stdin.write(line.encode('utf-8'))
mail.communicate()

gitrepo = os.environ.get('GL_REPO')
if gitrepo.startswith('packages/'):
    gitrepo = gitrepo[len('packages/'):]
else:
    sys.exit()

(tfile, name) = tempfile.mkstemp(prefix=gitrepo+'.', dir=WATCHDIR)

os.write(tfile,(gitrepo+'\n').encode('utf-8'))
os.write(tfile,''.join(data).encode('utf-8'))
os.close(tfile)
