#!/usr/bin/python3 -u

import fcntl
import os
import tempfile
import sys
import subprocess

from git_slug.refsdata import RemoteRefsData
from git_slug.gitconst import REFREPO, REFFILE
from git_slug.serverconst import WATCHDIR
from git_slug.gitrepo import GitRepo


data = sys.stdin.readlines()

if (os.path.isdir('hooks/post-receive.d')):
    for hook in os.listdir('hooks/post-receive.d'):
        hook = os.path.join('hooks/post-receive.d', hook)
        if (hook.endswith(('~','.bak','.rpmsave','.rpmnew')) or not os.access(hook, os.X_OK)):
            continue
        hook_process = subprocess.Popen([hook], stdin=subprocess.PIPE)
        for line in data:
            hook_process.stdin.write(line.encode('utf-8'))
        hook_process.communicate()

gitrepo = os.environ.get('GL_REPO')
if gitrepo.startswith('packages/'):
    gitrepo = gitrepo[len('packages/'):]
else:
    sys.exit()

(tfile, name) = tempfile.mkstemp(prefix=gitrepo+'.', dir=WATCHDIR)
os.write(tfile,(os.getenv('GL_USER')+'\n').encode('utf-8'))
os.write(tfile,(gitrepo+'\n').encode('utf-8'))
os.write(tfile,''.join(data).encode('utf-8'))
os.close(tfile)
